version: "3"

networks:
  himed_network:
    external: true

services:
  satusehat_kyc_api_kk:
    container_name: satusehat_kyc_api_kk
    image: rizan1998/satusehat_kyc_api_kk
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9500:80"
    volumes:
      - ./medisy-satusehat-master:/var/www
      - ./medisy-satusehat-master/public:/var/www/html
      - ./.env:/var/www/.env
      - ./medisy-satusehat-master/storage:/var/www/storage
    environment:
      - app_name=Satu sehat API
    networks:
      - himed_network

  satusehat_kyc_api_kk_queue:
    container_name: satusehat_kyc_api_kk_queue
    image: rizan1998/satusehat_kyc_api_kk
    restart: unless-stopped
    command: php artisan queue:work
    volumes:
      - ./medisy-satusehat-master:/var/www
      - ./medisy-satusehat-master/public:/var/www/html
      - ./.env:/var/www/.env
      - ./medisy-satusehat-master/storage:/var/www/storage
    networks:
      - himed_network

  # satusehat_api_mysql:
  #   container_name: satusehat_api_mysql
  #   restart: unless-stopped
  #   image: mysql:5.7.35
  #   ports:
  #     - "33500:3306"
  #   volumes:
  #     - ./docker/mysql:/var/lib/mysql
  #   environment:
  #     MYSQL_DATABASE: homestead
  #     MYSQL_USER: homestead
  #     MYSQL_PASSWORD: secret
  #     MYSQL_ROOT_PASSWORD: secret
  #   networks:
  #     - himed_network
  # phpmyadmin_satusehat_api:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin_satusehat_api
  #   restart: always
  #   ports:
  #     - "9501:80"
  #   environment:
  #     PMA_ARBITRARY: 1
  #     PMA_HOST: mysql
  #   networks:
  #     - himed_network
